---

repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.5.2
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    - id: check-merge-conflict
    - id: check-builtin-literals
    - id: check-docstring-first
    - id: check-yaml
    - id: check-toml
    - id: check-ast
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: double-quote-string-fixer
#    - id: requirements-txt-fixer

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear == 20.1.2
        language_version: python3.8

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.7.2
    hooks:
      - id: pyupgrade

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.720
    hooks:
    -   id: mypy
        exclude: ^(docs/|example-plugin/|tests/fixtures)
