---
name: Upload Python Package to TestPypi

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "Set up Python"
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: "Install dependencies"
      run: |
        set -xe
        python -VV
        python -m site
        python -m pip install --upgrade pip setuptools wheel
    - name: "Build package"
      run: |
        sed "s/VERSION =.*/VERSION = '${GITHUB_REF##*/}-$GITHUB_SHA'/g"
        python setup.py sdist bdist_wheel
    - name: "Publish package to TestPyPI"
      uses: pypa/gh-action-pypi-publish@master
      with:
        skip_existing: true
        user: __token__
        password: ${{ secrets.TESTPYPI_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
