---
name: "Master branch verification"

on:
  pull_request:
    branches:
      - master

jobs:
  tests:
    name: "Python ${{ matrix.python-version }}"
    runs-on: "ubuntu-latest"
    env:
      USING_COVERAGE: '3.6,3.8'

    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8"]

    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: "${{ matrix.python-version }}"
      - name: "Install dependencies"
        run: |
          set -xe
          python -VV
          python -m site
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --upgrade coverage[toml] virtualenv tox tox-gh-actions
      - name: "Run tox targets for ${{ matrix.python-version }}"
        run: tox
      - name: "Get coverage"
        run: |
          set -xe
          coverage xml
        if: "contains(env.USING_COVERAGE, matrix.python-version)"
      - name: "Upload coverage to Codecov"
        if: "contains(env.USING_COVERAGE, matrix.python-version)"
        uses: "codecov/codecov-action@v1"
        with:
          fail_ci_if_error: true
      - name: "Build package"
        run: |
          set -xe
          sed -i "s/VERSION =.*/VERSION = 'PR-$GITHUB_SHA::8'/g" ./src/yacfg/meta.py
          python setup.py sdist bdist_wheel
      - name: "Upload dist artifacts"
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: package-dist
          path: dist/

      - name: "Upload docs artifacts"
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: docs_html
          path: docs/_build/html
